#!/bin/bash

if [ -z "$(audtool playback-status)" ]; then
	audacious "$@" &
elif audtool playback-stopped; then
	audtool playlist-clear
	audtool playlist-addurl "$@"
	audtool playback-play
else
	audtool playlist-addurl "$@"
fi

