#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ip='ip -c'
alias ls='ls --color=auto'

export PS1='\u@\h:\w\$ '

stty werase undef
bind '\C-w:unix-filename-rubout'
