#!/bin/sh

export USER=`id -nu`

B='#00000000'  # blank
C='#ffffff22'  # clear ish
D='#ffffffcc'  # default
T='#eeeeeeee'  # text
K='#808080ee'  # key
W='#880000bb'  # wrong
V='#eeeeeeee'  # verifying

LC_ALL=C i3lock -n -e \
--insidevercolor=$C   \
--ringvercolor=$V     \
\
--insidewrongcolor=$C \
--ringwrongcolor=$W   \
\
--insidecolor=$B      \
--ringcolor=$D        \
--linecolor=$B        \
--separatorcolor=$D   \
\
--verifcolor=$T        \
--wrongcolor=$T        \
--timecolor=$T        \
--datecolor=$T        \
--layoutcolor=$T      \
--keyhlcolor=$K       \
--bshlcolor=$K        \
\
--screen 1            \
--blur 5              \
--clock               \
--indicator           \
--timestr="%H:%M:%S"  \
--datestr="%A, %Y-%m-%d" \
--veriftext="..."     \
--noinputtext=""      \
--wrongtext="Incorrect" \
--keylayout 2         \

# --veriftext="Drinking verification can..."
# --wrongtext="Nope!"
# --textsize=20
# --modsize=10
# --timefont=comic-sans
# --datefont=monofur
# etc
