set nocompatible " vim mode
set t_Co=256 " fick yeah
syntax enable " syntax highlighting
set encoding=utf-8 " goin' international
filetype plugin indent on " load file type plugins + indentation
filetype on " something with filetypes i guess?
set autoindent " precisely.
set si " smart indent. is it good? is it bad? i don't know. it seems to work well
set hlsearch " highlight search results
" dehighlights search results at the press of ,/
nmap <silent> ,/ :nohlsearch<CR>
set incsearch " jump to first result automagically

set nobackup " don't create backup files
set noswapfile " don't create the swap files (i save often enough anyway)
set title " set the terminal title according to the open buffer

set nostartofline " try to keep the column while jumping
set nowrap " don't wrap lines
set tabstop=8 shiftwidth=0
set softtabstop=-1
set noexpandtab
let g:detectindent_preferred_indent = 8 


set bs=indent,eol,start " backspace plows through everything
set ruler " linenumber and stuff at the bottom
set number " line numbers at the side

set hidden

call plug#begin('~/.vim/plugged')

Plug 'roryokane/detectindent'
Plug 'preservim/nerdtree'
Plug 'vim-ctrlspace/vim-ctrlspace'
Plug 'arrufat/vala.vim'
Plug 'easymotion/vim-easymotion'
Plug 'tikhomirov/vim-glsl'
Plug 'rafi/awesome-vim-colorschemes'
Plug 'vim-airline/vim-airline'
Plug 'bling/vim-bufferline'

call plug#end()

colorscheme minimalist

augroup PythonTabs
   autocmd!
   autocmd FileType python setlocal noexpandtab tabstop=8 shiftwidth=0 softtabstop=-1
augroup END

augroup DetectIndent
   autocmd!
   autocmd BufReadPost *  DetectIndent
augroup END
